#ifndef ITEM_IDS_H
#define ITEM_IDS_H


enum Item {
    ITEM_NONE = 0x0,
    ITEM_MASTER_BALL = 0x1,
    ITEM_ULTRA_BALL = 0x2,
    ITEM_GREAT_BALL = 0x3,
    ITEM_POKE_BALL = 0x4,
    ITEM_SAFARI_BALL = 0x5,
    ITEM_NET_BALL = 0x6,
    ITEM_DIVE_BALL = 0x7,
    ITEM_NEST_BALL = 0x8,
    ITEM_REPEAT_BALL = 0x9,
    ITEM_TIMER_BALL = 0xA,
    ITEM_LUXURY_BALL = 0xB,
    ITEM_PREMIER_BALL = 0xC,
    ITEM_POTION = 0xD,
    ITEM_ANTIDOTE = 0xE,
    ITEM_BURN_HEAL = 0xF,
    ITEM_ICE_HEAL = 0x10,
    ITEM_AWAKENING = 0x11,
    ITEM_PARALYZE_HEAL = 0x12,
    ITEM_FULL_RESTORE = 0x13,
    ITEM_MAX_POTION = 0x14,
    ITEM_HYPER_POTION = 0x15,
    ITEM_SUPER_POTION = 0x16,
    ITEM_FULL_HEAL = 0x17,
    ITEM_REVIVE = 0x18,
    ITEM_MAX_REVIVE = 0x19,
    ITEM_FRESH_WATER = 0x1A,
    ITEM_SODA_POP = 0x1B,
    ITEM_LEMONADE = 0x1C,
    ITEM_MOOMOO_MILK = 0x1D,
    ITEM_ENERGY_POWDER = 0x1E,
    ITEM_ENERGY_ROOT = 0x1F,
    ITEM_HEAL_POWDER = 0x20,
    ITEM_REVIVAL_HERB = 0x21,
    ITEM_ETHER = 0x22,
    ITEM_MAX_ETHER = 0x23,
    ITEM_ELIXIR = 0x24,
    ITEM_MAX_ELIXIR = 0x25,
    ITEM_LAVA_COOKIE = 0x26,
    ITEM_BLUE_FLUTE = 0x27,
    ITEM_YELLOW_FLUTE = 0x28,
    ITEM_RED_FLUTE = 0x29,
    ITEM_BLACK_FLUTE = 0x2A,
    ITEM_WHITE_FLUTE = 0x2B,
    ITEM_BERRY_JUICE = 0x2C,
    ITEM_SACRED_ASH = 0x2D,
    ITEM_SHOAL_SALT = 0x2E,
    ITEM_SHOAL_SHELL = 0x2F,
    ITEM_RED_SHARD = 0x30,
    ITEM_BLUE_SHARD = 0x31,
    ITEM_YELLOW_SHARD = 0x32,
    ITEM_GREEN_SHARD = 0x33,
    ITEM_HP_UP = 0x3F,
    ITEM_PROTEIN = 0x40,
    ITEM_IRON = 0x41,
    ITEM_CARBOS = 0x42,
    ITEM_CALCIUM = 0x43,
    ITEM_RARE_CANDY = 0x44,
    ITEM_PP_UP = 0x45,
    ITEM_ZINC = 0x46,
    ITEM_PP_MAX = 0x47,
    ITEM_GUARD_SPEC = 0x49,
    ITEM_DIRE_HIT = 0x4A,
    ITEM_X_ATTACK = 0x4B,
    ITEM_X_DEFEND = 0x4C,
    ITEM_X_SPEED = 0x4D,
    ITEM_X_ACCURACY = 0x4E,
    ITEM_X_SPECIAL = 0x4F,
    ITEM_POKE_DOLL = 0x50,
    ITEM_FLUFFY_TAIL = 0x51,
    ITEM_SUPER_REPEL = 0x53,
    ITEM_MAX_REPEL = 0x54,
    ITEM_ESCAPE_ROPE = 0x55,
    ITEM_REPEL = 0x56,
    ITEM_SUN_STONE = 0x5D,
    ITEM_MOON_STONE = 0x5E,
    ITEM_FIRE_STONE = 0x5F,
    ITEM_THUNDER_STONE = 0x60,
    ITEM_WATER_STONE = 0x61,
    ITEM_LEAF_STONE = 0x62,
    ITEM_TINY_MUSHROOM = 0x67,
    ITEM_BIG_MUSHROOM = 0x68,
    ITEM_PEARL = 0x6A,
    ITEM_BIG_PEARL = 0x6B,
    ITEM_STARDUST = 0x6C,
    ITEM_STAR_PIECE = 0x6D,
    ITEM_NUGGET = 0x6E,
    ITEM_HEART_SCALE = 0x6F,
    ITEM_PURPLE_JUICE = 0x71,
    ITEM_RED_JUICE = 0x72,
    ITEM_GREEN_JUICE = 0x73,
    ITEM_PINK_JUICE = 0x74,
    ITEM_YELLOW_JUICE = 0x75,
    ITEM_AWFUL_JUICE = 0x76,
    ITEM_SUPER_JUICE = 0x77,
    ITEM_ORANGE_MAIL = 0x79,
    ITEM_HARBOR_MAIL = 0x7A,
    ITEM_GLITTER_MAIL = 0x7B,
    ITEM_MECH_MAIL = 0x7C,
    ITEM_WOOD_MAIL = 0x7D,
    ITEM_WAVE_MAIL = 0x7E,
    ITEM_BEAD_MAIL = 0x7F,
    ITEM_SHADOW_MAIL = 0x80,
    ITEM_TROPIC_MAIL = 0x81,
    ITEM_DREAM_MAIL = 0x82,
    ITEM_FAB_MAIL = 0x83,
    ITEM_RETRO_MAIL = 0x84,
    ITEM_CHERI_BERRY = 0x85,
    ITEM_CHESTO_BERRY = 0x86,
    ITEM_PECHA_BERRY = 0x87,
    ITEM_RAWST_BERRY = 0x88,
    ITEM_ASPEAR_BERRY = 0x89,
    ITEM_LEPPA_BERRY = 0x8A,
    ITEM_ORAN_BERRY = 0x8B,
    ITEM_PERSIM_BERRY = 0x8C,
    ITEM_LUM_BERRY = 0x8D,
    ITEM_SITRUS_BERRY = 0x8E,
    ITEM_FIGY_BERRY = 0x8F,
    ITEM_WIKI_BERRY = 0x90,
    ITEM_MAGO_BERRY = 0x91,
    ITEM_AGUAV_BERRY = 0x92,
    ITEM_IAPAPA_BERRY = 0x93,
    ITEM_RAZZ_BERRY = 0x94,
    ITEM_BLUK_BERRY = 0x95,
    ITEM_NANAB_BERRY = 0x96,
    ITEM_WEPEAR_BERRY = 0x97,
    ITEM_PINAP_BERRY = 0x98,
    ITEM_POMEG_BERRY = 0x99,
    ITEM_KELPSY_BERRY = 0x9A,
    ITEM_QUALOT_BERRY = 0x9B,
    ITEM_HONDEW_BERRY = 0x9C,
    ITEM_GREPA_BERRY = 0x9D,
    ITEM_TAMATO_BERRY = 0x9E,
    ITEM_CORNN_BERRY = 0x9F,
    ITEM_MAGOST_BERRY = 0xA0,
    ITEM_RABUTA_BERRY = 0xA1,
    ITEM_NOMEL_BERRY = 0xA2,
    ITEM_SPELON_BERRY = 0xA3,
    ITEM_PAMTRE_BERRY = 0xA4,
    ITEM_WATMEL_BERRY = 0xA5,
    ITEM_DURIN_BERRY = 0xA6,
    ITEM_BELUE_BERRY = 0xA7,
    ITEM_LIECHI_BERRY = 0xA8,
    ITEM_GANLON_BERRY = 0xA9,
    ITEM_SALAC_BERRY = 0xAA,
    ITEM_PETAYA_BERRY = 0xAB,
    ITEM_APICOT_BERRY = 0xAC,
    ITEM_LANSAT_BERRY = 0xAD,
    ITEM_STARF_BERRY = 0xAE,
    ITEM_ENIGMA_BERRY = 0xAF,
    ITEM_BRIGHT_POWDER = 0xB3,
    ITEM_WHITE_HERB = 0xB4,
    ITEM_MACHO_BRACE = 0xB5,
    ITEM_EXP_SHARE = 0xB6,
    ITEM_QUICK_CLAW = 0xB7,
    ITEM_SOOTHE_BELL = 0xB8,
    ITEM_MENTAL_HERB = 0xB9,
    ITEM_CHOICE_BAND = 0xBA,
    ITEM_KINGS_ROCK = 0xBB,
    ITEM_SILVER_POWDER = 0xBC,
    ITEM_AMULET_COIN = 0xBD,
    ITEM_CLEANSE_TAG = 0xBE,
    ITEM_SOUL_DEW = 0xBF,
    ITEM_DEEP_SEA_TOOTH = 0xC0,
    ITEM_DEEP_SEA_SCALE = 0xC1,
    ITEM_SMOKE_BALL = 0xC2,
    ITEM_EVERSTONE = 0xC3,
    ITEM_FOCUS_BAND = 0xC4,
    ITEM_LUCKY_EGG = 0xC5,
    ITEM_SCOPE_LENS = 0xC6,
    ITEM_METAL_COAT = 0xC7,
    ITEM_LEFTOVERS = 0xC8,
    ITEM_DRAGON_SCALE = 0xC9,
    ITEM_LIGHT_BALL = 0xCA,
    ITEM_SOFT_SAND = 0xCB,
    ITEM_HARD_STONE = 0xCC,
    ITEM_MIRACLE_SEED = 0xCD,
    ITEM_BLACK_GLASSES = 0xCE,
    ITEM_BLACK_BELT = 0xCF,
    ITEM_MAGNET = 0xD0,
    ITEM_MYSTIC_WATER = 0xD1,
    ITEM_SHARP_BEAK = 0xD2,
    ITEM_POISON_BARB = 0xD3,
    ITEM_NEVER_MELT_ICE = 0xD4,
    ITEM_SPELL_TAG = 0xD5,
    ITEM_TWISTED_SPOON = 0xD6,
    ITEM_CHARCOAL = 0xD7,
    ITEM_DRAGON_FANG = 0xD8,
    ITEM_SILK_SCARF = 0xD9,
    ITEM_UP_GRADE = 0xDA,
    ITEM_SHELL_BELL = 0xDB,
    ITEM_SEA_INCENSE = 0xDC,
    ITEM_LAX_INCENSE = 0xDD,
    ITEM_LUCKY_PUNCH = 0xDE,
    ITEM_METAL_POWDER = 0xDF,
    ITEM_THICK_CLUB = 0xE0,
    ITEM_STICK = 0xE1,
    ITEM_MYSTERYTM01 = 0xE2,
    ITEM_MYSTERYTM02 = 0xE3,
    ITEM_MYSTERYTM03 = 0xE4,
    ITEM_MYSTERYTM04 = 0xE5,
    ITEM_MYSTERYTM05 = 0xE6,
    ITEM_MYSTERYTM06 = 0xE7,
    ITEM_MYSTERYTM07 = 0xE8,
    ITEM_MYSTERYTM08 = 0xE9,
    ITEM_MYSTERYTM09 = 0xEA,
    ITEM_MYSTERYTM10 = 0xEB,
    ITEM_MYSTERYTM11 = 0xEC,
    ITEM_MYSTERYTM12 = 0xED,
    ITEM_MYSTERYTM13 = 0xEE,
    ITEM_RED_SCARF = 0xFE,
    ITEM_BLUE_SCARF = 0xFF,
    ITEM_PINK_SCARF = 0x100,
    ITEM_GREEN_SCARF = 0x101,
    ITEM_YELLOW_SCARF = 0x102,
    ITEM_MACH_BIKE = 0x103,
    ITEM_COIN_CASE = 0x104,
    ITEM_ITEMFINDER = 0x105,
    ITEM_OLD_ROD = 0x106,
    ITEM_GOOD_ROD = 0x107,
    ITEM_SUPER_ROD = 0x108,
    ITEM_SS_TICKET = 0x109,
    ITEM_CONTEST_PASS = 0x10A,
    ITEM_WAILMER_PAIL = 0x10C,
    ITEM_DEVON_GOODS = 0x10D,
    ITEM_SOOT_SACK = 0x10E,
    ITEM_BASEMENT_KEY = 0x10F,
    ITEM_ACRO_BIKE = 0x110,
    ITEM_POKEBLOCK_CASE = 0x111,
    ITEM_LETTER = 0x112,
    ITEM_EON_TICKET = 0x113,
    ITEM_RED_ORB = 0x114,
    ITEM_BLUE_ORB = 0x115,
    ITEM_SCANNER = 0x116,
    ITEM_GO_GOGGLES = 0x117,
    ITEM_METEORITE = 0x118,
    ITEM_ROOM_1_KEY = 0x119,
    ITEM_ROOM_2_KEY = 0x11A,
    ITEM_ROOM_4_KEY = 0x11B,
    ITEM_ROOM_6_KEY = 0x11C,
    ITEM_STORAGE_KEY = 0x11D,
    ITEM_ROOT_FOSSIL = 0x11E,
    ITEM_CLAW_FOSSIL = 0x11F,
    ITEM_DEVON_SCOPE = 0x120,
    ITEM_TM01 = 0x121,
    ITEM_TM02 = 0x122,
    ITEM_TM03 = 0x123,
    ITEM_TM04 = 0x124,
    ITEM_TM05 = 0x125,
    ITEM_TM06 = 0x126,
    ITEM_TM07 = 0x127,
    ITEM_TM08 = 0x128,
    ITEM_TM09 = 0x129,
    ITEM_TM10 = 0x12A,
    ITEM_TM11 = 0x12B,
    ITEM_TM12 = 0x12C,
    ITEM_TM13 = 0x12D,
    ITEM_TM14 = 0x12E,
    ITEM_TM15 = 0x12F,
    ITEM_TM16 = 0x130,
    ITEM_TM17 = 0x131,
    ITEM_TM18 = 0x132,
    ITEM_TM19 = 0x133,
    ITEM_TM20 = 0x134,
    ITEM_TM21 = 0x135,
    ITEM_TM22 = 0x136,
    ITEM_TM23 = 0x137,
    ITEM_TM24 = 0x138,
    ITEM_TM25 = 0x139,
    ITEM_TM26 = 0x13A,
    ITEM_TM27 = 0x13B,
    ITEM_TM28 = 0x13C,
    ITEM_TM29 = 0x13D,
    ITEM_TM30 = 0x13E,
    ITEM_TM31 = 0x13F,
    ITEM_TM32 = 0x140,
    ITEM_TM33 = 0x141,
    ITEM_TM34 = 0x142,
    ITEM_TM35 = 0x143,
    ITEM_TM36 = 0x144,
    ITEM_TM37 = 0x145,
    ITEM_TM38 = 0x146,
    ITEM_TM39 = 0x147,
    ITEM_TM40 = 0x148,
    ITEM_TM41 = 0x149,
    ITEM_TM42 = 0x14A,
    ITEM_TM43 = 0x14B,
    ITEM_TM44 = 0x14C,
    ITEM_TM45 = 0x14D,
    ITEM_TM46 = 0x14E,
    ITEM_TM47 = 0x14F,
    ITEM_TM48 = 0x150,
    ITEM_TM49 = 0x151,
    ITEM_TM50 = 0x152,
    ITEM_HM01 = 0x153,
    ITEM_HM02 = 0x154,
    ITEM_HM03 = 0x155,
    ITEM_HM04 = 0x156,
    ITEM_HM05 = 0x157,
    ITEM_HM06 = 0x158,
    ITEM_HM07 = 0x159,
    ITEM_HM08 = 0x15A,
    ITEM_TM51 = 0x15B,
    ITEM_OAKSPARCEL = 0x15D,
    ITEM_POKEFLUTE = 0x15E,
    ITEM_SECRETKEY = 0x15F,
    ITEM_BIKEVOUCHER = 0x160,
    ITEM_GOLDTEETH = 0x161,
    ITEM_OLDAM_BER = 0x162,
    ITEM_CARDKEY = 0x163,
    ITEM_LIFTKEY = 0x164,
    ITEM_HELIXFOSSIL = 0x165,
    ITEM_DOMEFOSSIL = 0x166,
    ITEM_SILPHSCOPE = 0x167,
    ITEM_BICYCLE = 0x168,
    ITEM_TOWNMAP = 0x169,
    ITEM_VSSEEKER = 0x16A,
    ITEM_FAMECHECKER = 0x16B,
    ITEM_TMCASE = 0x16C,
    ITEM__BERRYPOUCH = 0x16D,
    ITEM_TEACHYTV = 0x16E,
    ITEM_TRIPASS = 0x16F,
    ITEM_RAINBOWPASS = 0x170,
    ITEM_TEA = 0x171,
    ITEM_MYSTICTICKET = 0x172,
    ITEM_AURORATICKET = 0x173,
    ITEM_POWDERJAR = 0x174,
    ITEM_RUBY = 0x175,
    ITEM_SAPPHIRE = 0x176,
    ITEM_MAGMAEMBLEM = 0x177,
    ITEM_OLDSEAMAP = 0x178,
    ITEM_MAX
};

enum HOLD_EFFECTS
{
      HOLD_EFFECT_NONE , //0x0
      HOLD_EFFECT_RESTORE_HP, //0x1
      HOLD_EFFECT_CURE_PAR, //0x2
      HOLD_EFFECT_CURE_SLP , //0x3
      HOLD_EFFECT_CURE_PSN , //0x4
      HOLD_EFFECT_CURE_BRN , //0x5
      HOLD_EFFECT_CURE_FRZ , //0x6
      HOLD_EFFECT_RESTORE_PP , //0x7
      HOLD_EFFECT_CURE_CONFUSION , //0x8
      HOLD_EFFECT_CURE_STATUS , //0x9
      HOLD_EFFECT_CONFUSE_SPICY , //0xA
      HOLD_EFFECT_CONFUSE_DRY , //0xB
      HOLD_EFFECT_CONFUSE_SWEET , //0xC
      HOLD_EFFECT_CONFUSE_BITTER , //0xD
      HOLD_EFFECT_CONFUSE_SOUR , //0xE
      HOLD_EFFECT_ATTACK_UP , //0xF
      HOLD_EFFECT_DEFENSE_UP , //0x10
      HOLD_EFFECT_SPEED_UP , //0x11
      HOLD_EFFECT_SP_ATTACK_UP , //0x12
      HOLD_EFFECT_SP_DEFENSE_UP , //0x13
      HOLD_EFFECT_CRITICAL_UP , //0x14
      HOLD_EFFECT_RANDOM_STAT_UP , //0x15
      HOLD_EFFECT_EVASION_UP , //0x16
      HOLD_EFFECT_RESTORE_STATS , //0x17
      HOLD_EFFECT_MACHO_BRACE , //0x18
      HOLD_EFFECT_EXP_SHARE , //0x19
      HOLD_EFFECT_QUICK_CLAW , //0x1A
      HOLD_EFFECT_HAPPINESS_UP , //0x1B
      HOLD_EFFECT_CURE_ATTRACT , //0x1C
      HOLD_EFFECT_CHOICE_BAND , //0x1D
      HOLD_EFFECT_FLINCH, //0x1E
      HOLD_EFFECT_BUG_POWER , //0x1F
      HOLD_EFFECT_DOUBLE_PRIZE , //0x20
      HOLD_EFFECT_REPEL , //0x21
      HOLD_EFFECT_SOUL_DEW , //0x22
      HOLD_EFFECT_DEEP_SEA_TOOTH , //0x23
      HOLD_EFFECT_DEEP_SEA_SCALE , //0x24
      HOLD_EFFECT_CAN_ALWAYS_RUN , //0x25
      HOLD_EFFECT_PREVENT_EVOLVE , //0x26
      HOLD_EFFECT_FOCUS_BAND , //0x27
      HOLD_EFFECT_LUCKY_EGG , //0x28
      HOLD_EFFECT_SCOPE_LENS , //0x29
      HOLD_EFFECT_STEEL_POWER , //0x2A
      HOLD_EFFECT_LEFTOVERS , //0x2B
      HOLD_EFFECT_DRAGON_SCALE , //0x2C
      HOLD_EFFECT_LIGHT_BALL , //0x2D
      HOLD_EFFECT_GROUND_POWER , //0x2E
      HOLD_EFFECT_ROCK_POWER , //0x2F
      HOLD_EFFECT_GRASS_POWER , //0x30
      HOLD_EFFECT_DARK_POWER , //0x31
      HOLD_EFFECT_FIGHTING_POWER , //0x32
      HOLD_EFFECT_ELECTRIC_POWER , //0x33
      HOLD_EFFECT_WATER_POWER , //0x34
      HOLD_EFFECT_FLYING_POWER , //0x35
      HOLD_EFFECT_POISON_POWER , //0x36
      HOLD_EFFECT_ICE_POWER , //0x37
      HOLD_EFFECT_GHOST_POWER , //0x38
      HOLD_EFFECT_PSYCHIC_POWER , //0x39
      HOLD_EFFECT_FIRE_POWER , //0x3A
      HOLD_EFFECT_DRAGON_POWER , //0x3B
      HOLD_EFFECT_NORMAL_POWER , //0x3C
      HOLD_EFFECT_UP_GRADE , //0x3D
      HOLD_EFFECT_SHELL_BELL , //0x3E
      HOLD_EFFECT_LUCKY_PUNCH , //0x3F
      HOLD_EFFECT_METAL_POWDER , //0x40
      HOLD_EFFECT_THICK_CLUB , //0x41
      HOLD_EFFECT_STICK , //0x42
      HOLD_EFFECT_CHOICESPECS = 0x47,
      HOLD_EFFECT_ADAMANTORB , //0x48
      HOLD_EFFECT_GRISEOUSORB , //0x49
      HOLD_EFFECT_LIFEORB , //0x4A
      HOLD_EFFECT_LUSTROUSORB , //0x4B
      HOLD_EFFECT_EVIOLITE , //0x4C
      HOLD_EFFECT_ASSAULTVEST , //0x4D
      HOLD_EFFECT_MUSCLEBAND , //0x4E
      HOLD_EFFECT_WISEGLASSES , //0x4F
      HOLD_EFFECT_PINKRIBBON , //0x50
      HOLD_EFFECT_RINGTARGET = 0x54,
      HOLD_EFFECT_EXPERTBELT , //0x55
      HOLD_EFFECT_WIDELENS  = 0x68,
      HOLD_EFFECT_ZOOMLENS , //0x69
      HOLD_EFFECT_FOCUSSASH , //0x6A
      HOLD_EFFECT_SAFETYGOOGLES , //0x6B
      HOLD_EFFECT_CHOICESCARF , //0x6C
      HOLD_EFFECT_LAGGINGTAIL , //0x6D
      HOLD_EFFECT_FLOAT_STONE , //0x6E
      HOLD_EFFECT_METRONOME , //0x6F
      HOLD_EFFECT_IRONBALL , //0x70
      HOLD_EFFECT_AIRBALLOON , //0x71
      HOLD_EFFECT_HEATROCK , //0x72
      HOLD_EFFECT_DAMPROCK , //0x73
      HOLD_EFFECT_SMOOTHROCK , //0x74
      HOLD_EFFECT_ICYROCK , //0x75
      HOLD_EFFECT_SITRUS_BERRY , //0x76
      HOLD_EFFECT_BLACKSLUDGE , //0x77
      HOLD_EFFECT_STICKYBARB , //0x78
      HOLD_EFFECT_FLAMEORB , //0x79
      HOLD_EFFECT_TOXICORB , //0x7A
      HOLD_EFFECT_WEAKNESSPOLICY , //0x7B
      HOLD_EFFECT_EJECTBUTTON , //0x7C
      HOLD_EFFECT_REDCARD , //0x7D
      HOLD_EFFECT_ROCKYHELMET , //0x7E
      HOLD_EFFECT_LIGHTCLAY , //0x7F
      HOLD_EFFECT_DESTINYKNOT , //0x80
      HOLD_EFFECT_LUMINOUSMOSS , //0x81
      HOLD_EFFECT_CELLBATTERY , //0x82
      HOLD_EFFECT_SNOWBALL , //0x83
      HOLD_EFFECT_ABSORBBULB , //0x84
      HOLD_EFFECT_QUICKPOWDER , //0x85
      HOLD_EFFECT_BIGROOT , //0x86
      HOLD_EFFECT_BINDINGBAND , //0x87
      HOLD_EFFECT_GRIPCLAW , //0x88
      HOLD_EFFECT_CUSTAP_BERRY , //0x89
      HOLD_EFFECT_POWERHERB , //0x8A
      HOLD_EFFECT_MEGA_STONE , //0x8B
      HOLD_EFFECT_DRIVES , //0x8C
      HOLD_EFFECT_PRIMALORB , //0x8D
      HOLD_EFFECT_SHEDSHELL , //0x8E
      HOLD_EFFECT_GEM , //0x8F //the extra is the type it boosts
      HOLD_EFFECT_DAM_REDUX__BERRY , //0x90 //the extra is the type it resists
      HOLD_EFFECT_PLATES , //0x91
      HOLD_EFFECT_MEMORIES, //0x92
      HOLD_EFFECT_TERRAINEXPANDER, //0x93
      HOLD_EFFECT_PROTECTIVEPADS, //0x94 moves dont make contact
      HOLD_EFFECT_ELECTRICSEED, //0x95
      HOLD_EFFECT_GRASSYSEED, //0x96
      HOLD_EFFECT_MISTYSEED, //0x97
      HOLD_EFFECT_PSYCHICSEED, //0x98
};


enum ItemPocket {
    ITEM_POCKET_NONE,
	ITEM_POCKET_ITEMS,
	ITEM_POCKET_POKE_BALLS,
	ITEM_POCKET_TM_HM,
	ITEM_POCKET_BERRIES,
    ITEM_POCKET_KEY_ITEMS,    
};

enum ItemGenericType {
    /**> _MAIL */
    ITEM_TYPE_GENERIC_MAIL,

    /**> Items which can be used out-of-battle. */
    ITEM_TYPE_GENERIC_OVERWORLD,

    /**> Items which can be assigned to select */
    ITEM_TYPE_GENERIC_REGISTER,

    /**> Only the Pokéblock case is of this type. */
    ITEM_TYPE_GENERIC_POKEBLOCK_CASE,

    /**> Items which cannot be used out-of-battle. */
    ITEM_TYPE_GENERIC_BATTLE,
};

enum ItemBallType {
    ITEM_TYPE_BALL_MASTER,
    ITEM_TYPE_BALL_ULTRA,
    ITEM_TYPE_BALL_GREAT,
    ITEM_TYPE_BALL_POKE,
    ITEM_TYPE_BALL_SAFARI,
    ITEM_TYPE_BALL_NET,
    ITEM_TYPE_BALL_DIVE,
    ITEM_TYPE_BALL_NEST,
    ITEM_TYPE_BALL_REPEAT,
    ITEM_TYPE_BALL_TIMER,
    ITEM_TYPE_BALL_LUXURY,
    ITEM_TYPE_BALL_PREMIER,
};

union ItemType {
    enum ItemGenericType item;
    enum ItemBallType ball;
};


struct ItemData {
    pchar name[14];
    u16 index;
    u16 market_price;
    u8 hold_effect;
    u8 quality;
    pchar* description;
    u8 is_unique;
    u8 mystery_value;
    enum ItemPocket pocket;
    union ItemType type;
    TaskCallback overworld_routine;
    u8 usage;
    u8 field_21;
    u16 field_22;
    TaskCallback battle_routine;
    u32 extra_param;
};




#endif /* ITEM_IDS */
