#ifndef I_REFS
#define I_REFS

#define NULL ((void *)0)
#define ItemUseOutOfBattle_Mail NULL
#define ItemUseOutOfBattle_EnigmaBerry NULL
#define ItemUseOutOfBattle_RareCandy NULL
#define ItemUseOutOfBattle_PPUp NULL
#define ItemUseOutOfBattle_Repel NULL
#define ItemUseOutOfBattle_EscapeRope NULL
#define ItemUseOutOfBattle_PokeblockCase NULL
#define ItemUseOutOfBattle_EvolutionStone NULL
#define ItemUseOutOfBattle_WailmerPail NULL
#define ItemUseOutOfBattle_CoinCase NULL
#define ItemUseOutOfBattle_Itemfinder NULL
#define ItemUseOutOfBattle_Bike NULL
#define ItemUseOutOfBattle_Rod NULL
#define ItemUseOutOfBattle_CannotUse NULL
#define ItemUseOutOfBattle_Medicine NULL
#define ItemUseOutOfBattle_PPRecovery NULL
#define ItemUseOutOfBattle_BlackWhiteFlute NULL
#define ItemUseOutOfBattle_SacredAsh NULL
#define ItemUseOutOfBattle_TMHM NULL
#define ItemUseOutOfBattle_TM_HM NULL
#define ItemUseInBattle_PokeBall NULL
#define ItemUseInBattle_Medicine NULL
#define ItemUseInBattle_PPRecovery NULL
#define ItemUseInBattle_StatIncrease NULL
#define ItemUseInBattle_Escape NULL
#define ItemUseInBattle_EnigmaBerry NULL

extern pchar gItemDescription_MasterBall[];
extern pchar gItemDescription_UltraBall[];
extern pchar gItemDescription_GreatBall[];
extern pchar gItemDescription_PokeBall[];
extern pchar gItemDescription_SafariBall[];
extern pchar gItemDescription_NetBall[];
extern pchar gItemDescription_DiveBall[];
extern pchar gItemDescription_NestBall[];
extern pchar gItemDescription_RepeatBall[];
extern pchar gItemDescription_TimerBall[];
extern pchar gItemDescription_LuxuryBall[];
extern pchar gItemDescription_PremierBall[];
extern pchar gItemDescription_Potion[];
extern pchar gItemDescription_Antidote[];
extern pchar gItemDescription_BurnHeal[];
extern pchar gItemDescription_IceHeal[];
extern pchar gItemDescription_Awakening[];
extern pchar gItemDescription_ParalyzeHeal[];
extern pchar gItemDescription_FullRestore[];
extern pchar gItemDescription_MaxPotion[];
extern pchar gItemDescription_HyperPotion[];
extern pchar gItemDescription_SuperPotion[];
extern pchar gItemDescription_FullHeal[];
extern pchar gItemDescription_Revive[];
extern pchar gItemDescription_MaxRevive[];
extern pchar gItemDescription_FreshWater[];
extern pchar gItemDescription_SodaPop[];
extern pchar gItemDescription_Lemonade[];
extern pchar gItemDescription_MoomooMilk[];
extern pchar gItemDescription_EnergyPowder[];
extern pchar gItemDescription_EnergyRoot[];
extern pchar gItemDescription_HealPowder[];
extern pchar gItemDescription_RevivalHerb[];
extern pchar gItemDescription_Ether[];
extern pchar gItemDescription_MaxEther[];
extern pchar gItemDescription_Elixir[];
extern pchar gItemDescription_MaxElixir[];
extern pchar gItemDescription_LavaCookie[];
extern pchar gItemDescription_BlueFlute[];
extern pchar gItemDescription_YellowFlute[];
extern pchar gItemDescription_RedFlute[];
extern pchar gItemDescription_BlackFlute[];
extern pchar gItemDescription_WhiteFlute[];
extern pchar gItemDescription_BerryJuice[];
extern pchar gItemDescription_SacredAsh[];
extern pchar gItemDescription_ShoalSalt[];
extern pchar gItemDescription_ShoalShell[];
extern pchar gItemDescription_RedShard[];
extern pchar gItemDescription_BlueShard[];
extern pchar gItemDescription_YellowShard[];
extern pchar gItemDescription_GreenShard[];
extern pchar gItemDescription_HPUp[];
extern pchar gItemDescription_Protein[];
extern pchar gItemDescription_Iron[];
extern pchar gItemDescription_Carbos[];
extern pchar gItemDescription_Calcium[];
extern pchar gItemDescription_RareCandy[];
extern pchar gItemDescription_PPUp[];
extern pchar gItemDescription_Zinc[];
extern pchar gItemDescription_PPMax[];
extern pchar gItemDescription_GuardSpec[];
extern pchar gItemDescription_DireHit[];
extern pchar gItemDescription_XAttack[];
extern pchar gItemDescription_XDefend[];
extern pchar gItemDescription_XSpeed[];
extern pchar gItemDescription_XAccuracy[];
extern pchar gItemDescription_XSpecial[];
extern pchar gItemDescription_PokeDoll[];
extern pchar gItemDescription_FluffyTail[];
extern pchar gItemDescription_SuperRepel[];
extern pchar gItemDescription_MaxRepel[];
extern pchar gItemDescription_EscapeRope[];
extern pchar gItemDescription_Repel[];
extern pchar gItemDescription_SunStone[];
extern pchar gItemDescription_MoonStone[];
extern pchar gItemDescription_FireStone[];
extern pchar gItemDescription_ThunderStone[];
extern pchar gItemDescription_WaterStone[];
extern pchar gItemDescription_LeafStone[];
extern pchar gItemDescription_TinyMushroom[];
extern pchar gItemDescription_BigMushroom[];
extern pchar gItemDescription_Pearl[];
extern pchar gItemDescription_BigPearl[];
extern pchar gItemDescription_Stardust[];
extern pchar gItemDescription_StarPiece[];
extern pchar gItemDescription_Nugget[];
extern pchar gItemDescription_HeartScale[];
extern pchar gItemDescription_OrangeMail[];
extern pchar gItemDescription_HarborMail[];
extern pchar gItemDescription_GlitterMail[];
extern pchar gItemDescription_MechMail[];
extern pchar gItemDescription_WoodMail[];
extern pchar gItemDescription_WaveMail[];
extern pchar gItemDescription_BeadMail[];
extern pchar gItemDescription_ShadowMail[];
extern pchar gItemDescription_TropicMail[];
extern pchar gItemDescription_DreamMail[];
extern pchar gItemDescription_FabMail[];
extern pchar gItemDescription_RetroMail[];
extern pchar gItemDescription_CheriBerry[];
extern pchar gItemDescription_ChestoBerry[];
extern pchar gItemDescription_PechaBerry[];
extern pchar gItemDescription_RawstBerry[];
extern pchar gItemDescription_AspearBerry[];
extern pchar gItemDescription_LeppaBerry[];
extern pchar gItemDescription_OranBerry[];
extern pchar gItemDescription_PersimBerry[];
extern pchar gItemDescription_LumBerry[];
extern pchar gItemDescription_SitrusBerry[];
extern pchar gItemDescription_FigyBerry[];
extern pchar gItemDescription_WikiBerry[];
extern pchar gItemDescription_MagoBerry[];
extern pchar gItemDescription_AguavBerry[];
extern pchar gItemDescription_IapapaBerry[];
extern pchar gItemDescription_RazzBerry[];
extern pchar gItemDescription_BlukBerry[];
extern pchar gItemDescription_NanabBerry[];
extern pchar gItemDescription_WepearBerry[];
extern pchar gItemDescription_PinapBerry[];
extern pchar gItemDescription_PomegBerry[];
extern pchar gItemDescription_KelpsyBerry[];
extern pchar gItemDescription_QualotBerry[];
extern pchar gItemDescription_HondewBerry[];
extern pchar gItemDescription_GrepaBerry[];
extern pchar gItemDescription_TamatoBerry[];
extern pchar gItemDescription_CornnBerry[];
extern pchar gItemDescription_MagostBerry[];
extern pchar gItemDescription_RabutaBerry[];
extern pchar gItemDescription_NomelBerry[];
extern pchar gItemDescription_SpelonBerry[];
extern pchar gItemDescription_PamtreBerry[];
extern pchar gItemDescription_WatmelBerry[];
extern pchar gItemDescription_DurinBerry[];
extern pchar gItemDescription_BelueBerry[];
extern pchar gItemDescription_LiechiBerry[];
extern pchar gItemDescription_GanlonBerry[];
extern pchar gItemDescription_SalacBerry[];
extern pchar gItemDescription_PetayaBerry[];
extern pchar gItemDescription_ApicotBerry[];
extern pchar gItemDescription_LansatBerry[];
extern pchar gItemDescription_StarfBerry[];
extern pchar gItemDescription_EnigmaBerry[];
extern pchar gItemDescription_BrightPowder[];
extern pchar gItemDescription_WhiteHerb[];
extern pchar gItemDescription_MachoBrace[];
extern pchar gItemDescription_ExpShare[];
extern pchar gItemDescription_QuickClaw[];
extern pchar gItemDescription_SootheBell[];
extern pchar gItemDescription_MentalHerb[];
extern pchar gItemDescription_ChoiceBand[];
extern pchar gItemDescription_KingsRock[];
extern pchar gItemDescription_SilverPowder[];
extern pchar gItemDescription_AmuletCoin[];
extern pchar gItemDescription_CleanseTag[];
extern pchar gItemDescription_SoulDew[];
extern pchar gItemDescription_DeepSeaTooth[];
extern pchar gItemDescription_DeepSeaScale[];
extern pchar gItemDescription_SmokeBall[];
extern pchar gItemDescription_Everstone[];
extern pchar gItemDescription_FocusBand[];
extern pchar gItemDescription_LuckyEgg[];
extern pchar gItemDescription_ScopeLens[];
extern pchar gItemDescription_MetalCoat[];
extern pchar gItemDescription_Leftovers[];
extern pchar gItemDescription_DragonScale[];
extern pchar gItemDescription_LightBall[];
extern pchar gItemDescription_SoftSand[];
extern pchar gItemDescription_HardStone[];
extern pchar gItemDescription_MiracleSeed[];
extern pchar gItemDescription_BlackGlasses[];
extern pchar gItemDescription_BlackBelt[];
extern pchar gItemDescription_Magnet[];
extern pchar gItemDescription_MysticWater[];
extern pchar gItemDescription_SharpBeak[];
extern pchar gItemDescription_PoisonBarb[];
extern pchar gItemDescription_NeverMeltIce[];
extern pchar gItemDescription_SpellTag[];
extern pchar gItemDescription_TwistedSpoon[];
extern pchar gItemDescription_Charcoal[];
extern pchar gItemDescription_DragonFang[];
extern pchar gItemDescription_SilkScarf[];
extern pchar gItemDescription_UpGrade[];
extern pchar gItemDescription_ShellBell[];
extern pchar gItemDescription_SeaIncense[];
extern pchar gItemDescription_LaxIncense[];
extern pchar gItemDescription_LuckyPunch[];
extern pchar gItemDescription_MetalPowder[];
extern pchar gItemDescription_ThickClub[];
extern pchar gItemDescription_Stick[];
extern pchar gItemDescription_RedScarf[];
extern pchar gItemDescription_BlueScarf[];
extern pchar gItemDescription_PinkScarf[];
extern pchar gItemDescription_GreenScarf[];
extern pchar gItemDescription_YellowScarf[];
extern pchar gItemDescription_MachBike[];
extern pchar gItemDescription_CoinCase[];
extern pchar gItemDescription_Itemfinder[];
extern pchar gItemDescription_OldRod[];
extern pchar gItemDescription_GoodRod[];
extern pchar gItemDescription_SuperRod[];
extern pchar gItemDescription_SSTicket[];
extern pchar gItemDescription_ContestPass[];
extern pchar gItemDescription_WailmerPail[];
extern pchar gItemDescription_DevonGoods[];
extern pchar gItemDescription_SootSack[];
extern pchar gItemDescription_BasementKey[];
extern pchar gItemDescription_AcroBike[];
extern pchar gItemDescription_PokeblockCase[];
extern pchar gItemDescription_Letter[];
extern pchar gItemDescription_EonTicket[];
extern pchar gItemDescription_RedOrb[];
extern pchar gItemDescription_BlueOrb[];
extern pchar gItemDescription_Scanner[];
extern pchar gItemDescription_GoGoggles[];
extern pchar gItemDescription_Meteorite[];
extern pchar gItemDescription_Room1Key[];
extern pchar gItemDescription_Room2Key[];
extern pchar gItemDescription_Room4Key[];
extern pchar gItemDescription_Room6Key[];
extern pchar gItemDescription_StorageKey[];
extern pchar gItemDescription_RootFossil[];
extern pchar gItemDescription_ClawFossil[];
extern pchar gItemDescription_DevonScope[];
extern pchar gItemDescription_TM01[];
extern pchar gItemDescription_TM02[];
extern pchar gItemDescription_TM03[];
extern pchar gItemDescription_TM04[];
extern pchar gItemDescription_TM05[];
extern pchar gItemDescription_TM06[];
extern pchar gItemDescription_TM07[];
extern pchar gItemDescription_TM08[];
extern pchar gItemDescription_TM09[];
extern pchar gItemDescription_TM10[];
extern pchar gItemDescription_TM11[];
extern pchar gItemDescription_TM12[];
extern pchar gItemDescription_TM13[];
extern pchar gItemDescription_TM14[];
extern pchar gItemDescription_TM15[];
extern pchar gItemDescription_TM16[];
extern pchar gItemDescription_TM17[];
extern pchar gItemDescription_TM18[];
extern pchar gItemDescription_TM19[];
extern pchar gItemDescription_TM20[];
extern pchar gItemDescription_TM21[];
extern pchar gItemDescription_TM22[];
extern pchar gItemDescription_TM23[];
extern pchar gItemDescription_TM24[];
extern pchar gItemDescription_TM25[];
extern pchar gItemDescription_TM26[];
extern pchar gItemDescription_TM27[];
extern pchar gItemDescription_TM28[];
extern pchar gItemDescription_TM29[];
extern pchar gItemDescription_TM30[];
extern pchar gItemDescription_TM31[];
extern pchar gItemDescription_TM32[];
extern pchar gItemDescription_TM33[];
extern pchar gItemDescription_TM34[];
extern pchar gItemDescription_TM35[];
extern pchar gItemDescription_TM36[];
extern pchar gItemDescription_TM37[];
extern pchar gItemDescription_TM38[];
extern pchar gItemDescription_TM39[];
extern pchar gItemDescription_TM40[];
extern pchar gItemDescription_TM41[];
extern pchar gItemDescription_TM42[];
extern pchar gItemDescription_TM43[];
extern pchar gItemDescription_TM44[];
extern pchar gItemDescription_TM45[];
extern pchar gItemDescription_TM46[];
extern pchar gItemDescription_TM47[];
extern pchar gItemDescription_TM48[];
extern pchar gItemDescription_TM49[];
extern pchar gItemDescription_TM50[];
extern pchar gItemDescription_HM01[];
extern pchar gItemDescription_HM02[];
extern pchar gItemDescription_HM03[];
extern pchar gItemDescription_HM04[];
extern pchar gItemDescription_HM05[];
extern pchar gItemDescription_HM06[];
extern pchar gItemDescription_HM07[];
extern pchar gItemDescription_HM08[];
extern pchar gItemDescription_Dummy[];

#endif
